###
GET http://localhost:3000 
###
POST http://localhost:1500
Content-Type: application/json

{
    "name": "charlie",
    "location": "chocolate factory"
}

###
# Create new user
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "securePassword123"
}

###
# Try to create user with same email (should fail)
POST http://localhost:1500/signup
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "anotherPassword"
}

###
# Setup
GET http://localhost:1500/setup